#!/usr/bin/env bash
# See the workflow file for more information
read -p "Are you sure you want to exit workflow mode? [y/N] " -re exitoption
if [[ "$exitoption" == "y" ]] || [[ "$exitoption" == "Y" ]]; then
	while read -re toload; do
		path="$(grep $toload $HOME/.config/workflow/modules | sed 's/[^ ]* *//')"
		if [[ -z "$path" ]]; then
			echo "WARNING: Module $toload was supposed to be loaded, but it is not specified in the modules file."
			continue
		fi
	    if [[ ! -e "$path" ]]; then
	        echo "WARNING: File $path (required by module $toload) does not exist."
	        continue
	    fi
		source "$path"
		end
		unset -f start end
	done < "$HOME/.config/workflow/modules.enabled"
	touch "$HOME/.config/workflow/.lock"
fi
